---
title: "residual_emissions_scenarios"
author: "William F. Lamb"
date: "5 12 2022"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# setwd("C:/Users/lamw/ownCloudPublications/_Submitted/The size and composition of residual emissions in integrated assessment scenarios at net zero CO2/")
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())
library(tidyverse)
library(readxl)
library(countrycode)
library(patchwork)
library(openxlsx)
library(ggh4x)
library(factoextra)

load("Data/scenario_data.RData")
load("C:/Users/lamw/ownCloud/Resources/data/cc_gwps.RData")
source("C:/Users/lamw/ownCloud/Resources/r/figure_style.R")

wb_figures <- createWorkbook()
wb_analysis <- createWorkbook()
wd_data <- createWorkbook()

```

``` {r functions}

median_and_range <- function(data,grouping_vars) {
  
  data <- data %>% 
    group_by_at(grouping_vars) %>% 
    summarise(median = signif(median(value),2),
              percentile_5th = signif(quantile(value, probs = c(0.05)),2),
              percentile_95th = signif(quantile(value, probs = c(0.95)),2)) %>% 
    mutate(value=paste0(median," [",percentile_5th,"-",percentile_95th,"]")) %>% 
    select(-median,-percentile_5th,-percentile_95th)
  
}

```


```{r resolve_scenario_sectors}


## identify gases in the scenario data
wd_scenarios_emissions <- data_r1 %>% 
  ungroup() %>% 
  mutate(gas=ifelse(grepl("CO2",var),"CO2",NA)) %>% 
  mutate(gas=ifelse(grepl("CH4",var),"CH4",gas)) %>% 
  mutate(gas=ifelse(grepl("N2O",var),"N2O",gas)) %>% 
  mutate(gas=ifelse(grepl("F-Gases",var),"F-Gases",gas)) %>% 
  mutate(gas=ifelse(grepl("Kyoto Gases",var),"Kyoto Gases",gas)) %>% 
  select(-region)


## join GWPs and calculate CO2e by sector
wd_scenarios_emissions <- left_join(wd_scenarios_emissions,cc_gwps %>% 
                                      select(gas,gwp100_ar6) %>% 
                                      mutate(gwp100_ar6=ifelse(gas=="CH4",27,gwp100_ar6)),by="gas")

wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  mutate(gwp100_ar6=ifelse(unit=="Mt CO2-equiv/yr",1,gwp100_ar6)) %>% 
  mutate(value=ifelse(unit=="kt N2O/yr",value/1000,value)) %>%   # N2O is in kt, not Mt 
  mutate(value_gwp=value*gwp100_ar6) %>% 
  select(-value,-gwp100_ar6)


## create unique scenario IDs
wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  mutate(id=paste0(model,"|",scenario)) %>% 
  select(id,everything()) %>% 
  arrange(id)


## exclude scenarios based on whether they have semi-detailed sector data
cc_sectors <- read.xlsx("Data/scenario_sector_mapping.xlsx",sheet=2)
cc_scenarios <- left_join(wd_scenarios_emissions,cc_sectors %>% select(var) %>% mutate(include=1),by="var")
cc_scenarios <- cc_scenarios %>% 
  ungroup() %>% 
  select(-unit,-gas) %>% 
  filter(year==2050) %>% 
  filter(include==1)
cc_scenarios <- spread(cc_scenarios,var,value_gwp)
# Manually fill Emissions|CO2|Other as this is important for resolving totals in some scenarios, but isn't universally available
cc_scenarios <- cc_scenarios %>% 
  mutate(`Emissions|CO2|Other`=ifelse(is.na(`Emissions|CO2|Other`),0,`Emissions|CO2|Other`))
cc_scenarios <- cc_scenarios %>% 
  na.omit() %>% 
  select(id)

wd_scenarios_emissions <- left_join(wd_scenarios_emissions,cc_scenarios %>% mutate(include=1),by="id") %>% 
  filter(include==1) %>% 
  select(-include)


## rejoin the list of emissions sectors
wd_scenarios_emissions <- left_join(wd_scenarios_emissions,cc_sectors,by=join_by(var,gas))


# infill the Emissions|CO2|Other sector
wd_co2_other_fix <- wd_scenarios_emissions %>% 
  ungroup() %>% 
  filter(var=="Emissions|CO2") %>% 
  select(id,model,scenario,category,unit,year)
wd_co2_other_fix <- left_join(wd_co2_other_fix,wd_scenarios_emissions %>% 
                                ungroup() %>% 
                                filter(var=="Emissions|CO2|Other") %>%
                                select(id,model,scenario,category,unit,year,value_gwp),
                              by = join_by(id, model, scenario, category, unit, year))
wd_co2_other_fix <- wd_co2_other_fix %>% 
  mutate(var="Emissions|CO2|Other") %>% 
  mutate(value_gwp=ifelse(is.na(value_gwp),0,value_gwp)) %>% 
  mutate(gas="CO2") %>% 
  mutate(sector="Other") %>% 
  mutate(subsector="Total")

wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  filter(var!="Emissions|CO2|Other")
wd_scenarios_emissions <- rbind(wd_scenarios_emissions,wd_co2_other_fix)

blarg <- wd_scenarios_emissions %>% filter(id=="IMAGE 3.0|EN_NPi2020_1000") %>% filter(year==2050)

## resolve sector and gas inconsistencies
wd_sector_totals <- wd_scenarios_emissions %>% 
  ungroup() %>% 
  filter(subsector=="Total") %>% 
  group_by(id,model,scenario,year,gas,sector) %>% 
  summarise(sector_total=sum(value_gwp)) 

wd_gas_totals <- wd_scenarios_emissions %>% 
  ungroup() %>% 
  filter(sector=="Total") %>% 
  group_by(id,model,scenario,year,gas) %>% 
  summarise(gas_total=sum(value_gwp))

###
blarg <- wd_scenarios_emissions %>% 
  filter(!is.na(gas)) %>% 
  arrange(year,var)
  
wd <- wd_scenarios_emissions %>% 
  filter(!is.na(sector)) %>%
  filter(!is.na(subsector)) %>%
  filter(subsector!="Total") %>%
  group_by(id,model,scenario,category,var,gas,sector,subsector,year) %>%
  summarise(value_gwp=sum(value_gwp,na.rm=TRUE)) %>% 
  arrange(year,var)

# sector inconsistencies
wd <- full_join(wd,wd_sector_totals,
                by = join_by(id, model, scenario,year,gas,sector)) %>% 
  arrange(id,year,var)

wd <- wd %>%
  mutate(value_gwp=ifelse(is.na(subsector),sector_total,value_gwp)) %>%
  mutate(subsector=ifelse(is.na(subsector),"Other",subsector))

residuals <- wd %>%
  group_by(id,model,scenario,year,gas,sector) %>%
  summarise(value_gwp=sum(value_gwp),sector_total=first(sector_total)) %>%
  mutate(value_gwp=sector_total-value_gwp) %>%
  mutate(subsector="Other") %>%
  select(-sector_total)# %>%
  #filter(value_gwp>0)

wd <- rbind(wd,residuals)
# 
# wd <- wd %>% 
#   group_by(id,model,scenario,category,year,gas,sector,subsector) %>% 
#   summarise(value_gwp=sum(value_gwp))

## gas inconsistencies
wd <- left_join(wd,wd_gas_totals,
                by = join_by(id, model, scenario, year, gas))


residuals <- wd %>%
  group_by(id,model,scenario,year,gas) %>%
  summarise(value_gwp=sum(value_gwp),gas_total=first(gas_total))%>%
  mutate(value_gwp=gas_total-value_gwp) %>%
  mutate(sector="Other") %>%
  select(-gas_total) #%>%
  #filter(value_gwp>0)

wd <- rbind(wd,residuals)
wd <- wd %>% 
  arrange(id,year,gas,sector)

## tidy up naming conventions

wd_scenarios_emissions <- wd %>% 
  mutate(var=ifelse(sector=="Other",paste0(gas,"|",sector),paste0(gas,"|",sector,"|",subsector))) %>% 
  mutate(var=ifelse(var=="F-Gases|F-Gases|Other","F-Gases",var)) %>% 
  mutate(var=ifelse(var=="CO2|AFOLU|Other","CO2|AFOLU",var)) %>% 
  mutate(var=ifelse(var=="N2O|AFOLU|Other","N2O|AFOLU",var)) %>% 
  mutate(var=ifelse(var=="CH4|Energy|Other","CH4|Energy",var)) %>% 
  mutate(var=ifelse(var=="CO2|Industrial processes|Other","CO2|Industrial processes",var)) %>% 
  mutate(var=ifelse(gas=="F-Gases","F-Gases",var)) %>%
  mutate(var=ifelse(gas=="Kyoto Gases","Kyoto Gases",var)) %>% 
  mutate(subsector=ifelse(is.na(subsector),"Other",subsector)) %>% 
  mutate(sector=ifelse(gas=="F-Gases","F-Gases",sector)) %>% 
  mutate(sector=ifelse(gas=="Kyoto Gases","Total",sector))

wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  group_by(id,model,scenario) %>% 
  mutate(category=first(category))

wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  group_by(id,model,scenario,category,year,var,gas,sector,subsector) %>% 
  summarise(value_gwp=sum(value_gwp,na.rm=TRUE))

## save the updated list of sectors
cc_sectors <- wd_scenarios_emissions %>% 
  ungroup() %>% 
  select(gas,sector,subsector,var) %>% 
  distinct()


```

```{r check_net_emissions}

## check if the bottom-up estimated totals equal the original reporting

check_co2 <- wd_scenarios_emissions %>% 
  group_by(id,year,gas) %>% 
  summarise(value=sum(value_gwp,na.rm=TRUE))

check_co2_native <- data_r1 %>% 
  filter(var %in% c("Emissions|CO2",
                    "Emissions|CH4",
                    "Emissions|N2O",
                    "Emissions|F-Gases")) %>%
  mutate(id=paste0(model,"|",scenario)) %>%
  ungroup() %>%
  select(id,year,var,value_native=value)

check_co2_native <- check_co2_native %>% 
  mutate(gas=ifelse(grepl("CO2",var),"CO2",NA)) %>% 
  mutate(gas=ifelse(grepl("CH4",var),"CH4",gas)) %>% 
  mutate(gas=ifelse(grepl("N2O",var),"N2O",gas)) %>% 
  mutate(gas=ifelse(grepl("F-Gases",var),"F-Gases",gas))

check_co2_native <- check_co2_native %>% 
  mutate(value_native=ifelse(gas=="CH4",value_native*27,value_native)) %>% 
  mutate(value_native=ifelse(gas=="N2O",(value_native*273.0)/1000,value_native))
  

check_co2 <- left_join(check_co2,check_co2_native %>% select(-var))
check_co2 <- check_co2 %>% 
  mutate(difference=value-value_native) %>% 
  filter(abs(difference)>1)



## Check for major discrepancies between the reconstructed sectors and the Kyoto gas total
check_kyoto <- wd_scenarios_emissions %>%
  filter(gas!="Kyoto Gases") %>%
  group_by(id,year) %>%
  summarise(recalculated_net_emissions=sum(value_gwp,na.rm=TRUE))

check_kyoto <- left_join(check_kyoto,wd_scenarios_emissions %>% 
                           ungroup %>% 
                           filter(gas=="Kyoto Gases") %>% 
                           filter(sector=="Total") %>% 
                           select(id,year,native_net_emissions=value_gwp),
                         by = join_by(id,year))

check_kyoto <- check_kyoto %>%
  mutate(difference=recalculated_net_emissions-native_net_emissions) %>%
  mutate(difference_abs=abs(difference))

check_kyoto <- left_join(check_kyoto,cc_scenarios %>% select(id) %>% mutate(include=1)) %>% 
  filter(include==1) %>% 
  select(-include)

check_kyoto <- check_kyoto %>%
  group_by(year) %>%
  summarise(median=signif(median(difference_abs),2),
            percentile_5th = signif(quantile(difference_abs, probs = c(0.05)),2),
            percentile_95th = signif(quantile(difference_abs, probs = c(0.95)),2))



```



```{r resolve_gross_emissions_and_removals}

## filter scenarios
wd_scenarios_removals <- data_r1 %>% 
  ungroup() %>% 
  mutate(id=paste0(model,"|",scenario)) %>% 
  select(id,everything(),-region,-unit) %>% 
  rename(value_gwp=value) %>% 
  arrange(id)

wd_scenarios_removals <- left_join(wd_scenarios_removals,cc_scenarios %>% mutate(include=1),by="id") %>% 
  filter(include==1) %>% 
  select(-include)


## identify relevant sectors
cc_removals <- read.xlsx("Data/scenario_sector_mapping.xlsx",sheet=3)
wd_scenarios_removals <- left_join(wd_scenarios_removals,cc_removals %>% mutate(include=1),by="var")
wd_scenarios_removals <- wd_scenarios_removals %>% 
  filter(include==1) %>% 
  select(-include)


## subtract CCS|Biomass|industrial processes from CCS|Biomass, so that the former aren't double counted when allocated to the process sector
wd_scenarios_removals <- spread(wd_scenarios_removals,var,value_gwp)
wd_scenarios_removals <- wd_scenarios_removals %>%
  mutate(`Carbon Sequestration|CCS|Biomass|Industrial Processes`=ifelse(is.na(`Carbon Sequestration|CCS|Biomass|Industrial Processes`),0,`Carbon Sequestration|CCS|Biomass|Industrial Processes`)) %>% 
  mutate(`Carbon Sequestration|CCS|Biomass`=`Carbon Sequestration|CCS|Biomass`-`Carbon Sequestration|CCS|Biomass|Industrial Processes`)


## merge the other removal categories
wd_scenarios_removals <- wd_scenarios_removals %>% 
  rowwise() %>% 
  mutate(`Carbon Sequestration|Other`= sum(`Carbon Sequestration|Direct Air Capture`,
                                           `Carbon Sequestration|Enhanced Weathering`,
                                           `Carbon Sequestration|Feedstocks`,
                                           `Carbon Sequestration|Other`,na.rm = TRUE))


## update the scenario inclusion list to exclude scenarios without land use removals reporting 
cc_scenarios <- anti_join(cc_scenarios,wd_scenarios_removals %>% filter(is.na(`Carbon Sequestration|Land Use`)) %>% select(id))


## tidy up 
wd_scenarios_removals <- gather(wd_scenarios_removals,var,value_gwp,`Carbon Sequestration|CCS|Biomass`:`Carbon Sequestration|Other`) %>% 
  filter(var %in% c("Carbon Sequestration|CCS|Biomass",
                    "Carbon Sequestration|CCS|Biomass|Industrial Processes",
                    "Carbon Sequestration|Land Use",
                    "Carbon Sequestration|Other"))


## join data to main dataset
wd_scenarios_emissions <- rbind(wd_scenarios_emissions,wd_scenarios_removals) %>% 
  arrange(id,year,var)


## check whats going on with IMAGE / Industrial process CCS
# check_ind <- wd_scenarios_emissions %>%
#   filter(id=="IMAGE 3.2|SSP1_SPA1_19I_D_LB") %>%
#   filter(var %in% c("CO2|Industrial processes",
#                     "Carbon Sequestration|CCS|Biomass|Industrial Processes",
#                     "CO2|Other"))
# 
# ggplot(check_ind,aes(x=year,y=value,color=var)) +
#   geom_path()


## calculate gross emissions by sector 
wd <- spread(wd_scenarios_emissions %>% 
                  ungroup() %>% 
                  select(id,model,scenario,category,year,var,value_gwp),var,value_gwp)

wd <- wd %>% 
  mutate(`CO2|Energy|Supply`=`CO2|Energy|Supply`+`Carbon Sequestration|CCS|Biomass`) %>% 
  mutate(`CO2|AFOLU`=`CO2|AFOLU`+`Carbon Sequestration|Land Use`) %>% 
  mutate(`CO2|Other`=`CO2|Other`+`Carbon Sequestration|Other`) %>% 
  mutate(`CO2|Other`=`CO2|Other`+`Carbon Sequestration|CCS|Biomass|Industrial Processes`)

wd <- gather(wd,var,value,-id,-model,-scenario,-category,-year)
wd <- left_join(wd,cc_sectors,by="var")
wd <- wd %>% 
  select(id,model,scenario,category,var,gas,sector,subsector,year,value) %>% 
  arrange(id,year,var)


## source the net zero years from scenario metadata
cc_netzero <- read.xlsx("Data/AR6_Scenarios_Database_metadata_indicators_v1.1_1.xlsx",sheet=2) %>% 
  mutate(id=paste0(Model,"|",Scenario)) %>% 
  select(id,net_zero_CO2=`Year.of.netzero.CO2.emissions.(Harm-Infilled).Table.SPM2`,
         net_zero_GHG=`Year.of.netzero.GHG.emissions.(Harm-Infilled).Table.SPM2`)
cc_netzero <- left_join(cc_netzero,cc_scenarios %>% mutate(include=1),by="id") %>% 
  filter(include==1) %>% 
  select(-include)

wd <- left_join(wd,cc_netzero,by="id")


## exclude the scenarios that don't reach net zero by 2100 and tidy up
wd <- wd %>% 
  filter(!is.na(net_zero_CO2)) %>% 
  arrange(id,year) %>% 
  mutate(value=value/1000)

no_scenarios <- wd %>% 
  select(id) %>%
  distinct()


## simplify the model names

wd_scenarios_emissions <- wd %>% 
  mutate(model=ifelse(grepl("IMAGE",model),"IMAGE",model)) %>% 
  mutate(model=ifelse(grepl("MESSAGE",model),"MESSAGE",model)) %>% 
  mutate(model=ifelse(grepl("REMIND",model),"REMIND",model))


wd_scenarios_emissions$category <- as.factor(wd_scenarios_emissions$category)
wd_scenarios_emissions$category <- fct_relevel(wd_scenarios_emissions$category,"C3","C2","C1")


wd_scenarios_emissions$gas <- as.factor(wd_scenarios_emissions$gas)
wd_scenarios_emissions$gas <- fct_relevel(wd_scenarios_emissions$gas,"CO2","CH4","N2O","F-Gases")


wd_scenarios_emissions$sector <- as.factor(wd_scenarios_emissions$sector)
wd_scenarios_emissions$sector <- fct_relevel(wd_scenarios_emissions$sector,"Energy","AFOLU","Industrial processes","F-Gases","Other")


```

```{r check_net_zero_years}

wd_check <- wd_scenarios_emissions %>% 
  filter(gas=="CO2") %>% 
  group_by(id,year,net_zero_CO2) %>% 
  summarise(value=sum(value,na.rm=TRUE))

wd_check <- left_join(wd_check,wd_scenarios_emissions %>% 
                     filter(grepl("Carbon Sequestration",var)) %>% 
                     group_by(id,year) %>% 
                     summarise(removals=sum(value,na.rm=TRUE)))

wd_check <- wd_check %>% 
  mutate(totals=value-removals)

####
wd_check <- left_join(wd_check,data_r1 %>% 
                     ungroup() %>% 
                     mutate(id=paste0(model,"|",scenario)) %>%
                     filter(var=="Emissions|CO2") %>%
                     mutate(value=value/1000) %>% 
                     select(id,year,native_co2=value),
                   by = join_by(id, year))

wd_check <- wd_check %>% 
  mutate(difference=totals-native_co2)

wd_check <- left_join(wd_check,data_r1 %>% 
                     ungroup() %>% 
                     mutate(id=paste0(model,"|",scenario)) %>%
                     filter(var=="AR6 climate diagnostics|Infilled|Emissions|CO2") %>%
                     mutate(value=value/1000) %>% 
                     select(id,year,infilled_co2=value),
                   by = join_by(id, year))

wd_check_years <- wd_check %>% 
  filter(totals<0) %>% 
  group_by(id) %>% 
  summarise(native_net_zero_CO2=first(year))

wd_check <- left_join(wd_check,wd_check_years)

wd_scenarios_emissions <- left_join(wd_scenarios_emissions,wd_check_years,by="id")
wd_scenarios_emissions <- wd_scenarios_emissions %>% 
  mutate(native_net_zero_CO2=ifelse(is.na(native_net_zero_CO2),2100,native_net_zero_CO2))

wd_check <- wd_scenarios_emissions %>% 
  select(id,native_net_zero_CO2,net_zero_CO2) %>% 
  distinct() %>% 
  mutate(difference=native_net_zero_CO2-net_zero_CO2) %>% 
  mutate(group="group") %>% 
  group_by(group) %>% 
  summarise(median=signif(median(difference),2),
            percentile_5th = signif(quantile(difference, probs = c(0.05)),2),
            percentile_95th = signif(quantile(difference, probs = c(0.95)),2))
  


```


```{r check_gross_negative}

## any scenarios where final gross emissions by sector are still negative?

check <- wd_scenarios_emissions %>%
  # mutate(include=ifelse(year==net_zero_CO2,1,0)) %>% 
  # filter(include==1) %>% 
  filter(year==2100) %>% 
  filter(var=="CO2|AFOLU") %>% 
  filter(value<0) %>% 
  select(id,model,var,value) %>% 
  mutate(group="blarg")

check <- median_and_range(check,"group")


```



```{r plot_totals,fig.height=6,fig.width=5,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

colors=c("#e6550d","#3182bd","#31a354")

## gross CO2 emissions at net zero CO2
wd_totals_co2 <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  filter(gas=="CO2") %>% 
  mutate(value=ifelse(is.na(value),0,value)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>% 
  group_by(id,category,year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(var="CO2")


## gross GHG emissions at net zero CO2
wd_totals_ghg <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(value=ifelse(is.na(value),0,value)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>% 
  group_by(id,category,year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(var="GHG")


## join
wd_totals <- rbind(wd_totals_co2,wd_totals_ghg) %>% 
  select(id,category,year,var,value) %>% 
            arrange(var,desc(category))


# labels
wd_totals <- wd_totals %>% 
  mutate(category=as.character(category)) %>% 
  mutate(category=ifelse(grepl("C1",category),"C1: Below 1.5°C",category)) %>% 
  mutate(category=ifelse(grepl("C2",category),"C2: Below 1.5°C with overshoot",category)) %>% 
  mutate(category=ifelse(grepl("C3",category),"C3: Below 2°C",category)) %>% 
  mutate(category=as.factor(category))

wd_totals$category <- fct_relevel(wd_totals$category,
                                  "C3: Below 2°C",
                                  "C2: Below 1.5°C with overshoot",
                                  "C1: Below 1.5°C") 


## plot CO2
p1 <- wd_totals %>% 
  filter(var=="CO2") %>% 
  ggplot(.,aes(x=value,fill=category)) +
  geom_density(alpha=0.3,color='#636363') +
  scale_x_continuous(limits=c(0,30),breaks=c(0,5,10,15,20,25,30)) +
  scale_fill_manual(values=colors) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.border = element_rect(color='#636363',fill=NA),
        panel.background = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color='#f0f0f0'),
        legend.position = "none",
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        plot.title = element_text(color='#636363',size = 14,face = 'bold'),
        plot.subtitle = element_text(color='#636363')) +
  labs(title=bquote(bold("a. Residual"~CO[2]*" emissions at net zero")),
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

p2 <- wd_totals %>% 
  filter(var=="CO2") %>% 
  ggplot(.,aes(x=value,y=category,fill=category)) +
  geom_point(shape=21,size=3,alpha=0.4,color="#636363") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 17)) +
  scale_fill_manual(values=colors) +
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm")) +
  scale_x_continuous(limits=c(0,30),breaks=c(0,5,10,15,20,25,30))


## plot GHG
p3 <- wd_totals %>% 
  filter(var=="GHG") %>% 
  ggplot(.,aes(x=value,fill=category)) +
  geom_density(alpha=0.3,color='#636363') +
  scale_x_continuous(limits=c(0,30),breaks=c(0,5,10,15,20,25,30)) +
  scale_fill_manual(values=colors) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.border = element_rect(color='#636363',fill=NA),
        panel.background = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color='#f0f0f0'),
        legend.position = "none",
        plot.background = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        plot.title = element_text(color='#636363',size = 14,face = 'bold'),
        plot.subtitle = element_text(color='#636363')) +
  labs(title=bquote(bold("b. Residual GHG emissions at net zero")),
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

p4 <- wd_totals %>% 
  filter(var=="GHG") %>% 
  ggplot(.,aes(x=value,y=category,fill=category)) +
  geom_point(shape=21,size=3,alpha=0.4,color="#636363") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 17)) +
  scale_fill_manual(values=colors) +
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm")) +
  scale_x_continuous(limits=c(0,30),breaks=c(0,5,10,15,20,25,30))


p1/plot_spacer()/p2/p3/plot_spacer()/p4 + plot_layout(heights=c(1.8,-0.5,4,1.8,-0.5,4))


## save plot data
addWorksheet(wb_figures,"fig_1_total_residual")
writeData(wb_figures, sheet = "fig_1_total_residual",
          wd_totals, colNames = T, rowNames = F)



```

```{r summary_table_totals}


## summary of scenario totals
wd_totals_summary <- median_and_range(wd_totals,c("var","category"))

wd_totals_summary <- left_join(wd_totals_summary,wd_totals %>% 
  group_by(var,category) %>% 
  summarise(n=n(),
            year_median = signif(median(year),4),
            year_5th = signif(quantile(year, probs = c(0.05)),4),
            year_95th = signif(quantile(year, probs = c(0.95)),4)) %>% 
  mutate(year=paste0(year_median," [",year_5th,"-",year_95th,"]")) %>% 
  select(var,category,year,n),by = join_by(var, category))


wd_totals_summary <- rbind(wd_totals_summary,
                           left_join(median_and_range(wd_totals,"var"),wd_totals %>% 
                     group_by(var) %>% 
                     summarise(n=n(),year_median = signif(median(year),4),
                               year_5th = signif(quantile(year, probs = c(0.05)),4),
                               year_95th = signif(quantile(year, probs = c(0.95)),4)) %>% 
                     mutate(year=paste0(year_median," [",year_5th,"-",year_95th,"]")) %>% 
                     select(var,year,n),by = join_by(var)) %>% 
                       mutate(category="all"))


## calculate reductions and join
wd_total_reductions <- wd_scenarios_emissions %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>% 
  filter(gas=="CO2") %>% 
  group_by(id,gas,category,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))

wd_total_reductions <- rbind(wd_total_reductions,wd_scenarios_emissions %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  group_by(id,category,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
    mutate(gas="GHG"))

wd_total_reductions <- wd_total_reductions %>% 
  group_by(id,gas,category) %>% 
  summarise(rel_change=(first(value)-last(value))/first(value)) %>% 
  mutate(rel_change=rel_change*100)


wd_total_reductions_summary <- median_and_range(wd_total_reductions %>% mutate(value=rel_change),c("gas","category"))
wd_total_reductions_summary <- rbind(wd_total_reductions_summary,
                                     median_and_range(wd_total_reductions %>% mutate(value=rel_change),c("gas")) %>% 
                                       mutate(category="all"))

wd_total_reductions_summary <- wd_total_reductions_summary %>% 
  mutate(category=as.character(category)) %>% 
  mutate(category=ifelse(grepl("C1",category),"C1: Below 1.5°C",category)) %>% 
  mutate(category=ifelse(grepl("C2",category),"C2: Below 1.5°C with overshoot",category)) %>% 
  mutate(category=ifelse(grepl("C3",category),"C3: Below 2°C",category)) %>% 
  mutate(category=as.factor(category))

wd_totals_summary <- left_join(wd_totals_summary %>% rename(residual=value,gas=var),
                               wd_total_reductions_summary %>% rename(reductions=value),
                               by = join_by(gas,category))


wd_totals_summary <- gather(wd_totals_summary,var,value,residual,reductions)
wd_totals_summary <- wd_totals_summary %>% 
  ungroup() %>% 
  mutate(var=paste0(gas,"_",var)) %>% 
  select(-gas)
wd_totals_summary <- spread(wd_totals_summary,var,value)
wd_totals_summary <- wd_totals_summary %>% 
  select(category,n,year,CO2_residual,CO2_reductions,GHG_residual,GHG_reductions)

addWorksheet(wb_analysis,"total_residual_at_nz")
writeData(wb_analysis, sheet = "total_residual_at_nz",
          wd_totals_summary, colNames = T, rowNames = F)


## standard deviations

wd_sd_summary <- wd_totals %>% 
  group_by(category,var) %>% 
  summarise(year_median = signif(median(year),4),
            year_5th = signif(quantile(year, probs = c(0.05)),4),
            year_95th = signif(quantile(year, probs = c(0.95)),4),
            year_sd = signif(sd(year),2),
            value_median = signif(median(value),2),
            value_5th = signif(quantile(value, probs = c(0.05)),2),
            value_95th = signif(quantile(value, probs = c(0.95)),2),
            value_sd = signif(sd(value),2)) %>% 
  mutate(year=paste0(year_median," [",year_5th,"-",year_95th,"]")) %>% 
  mutate(value=paste0(value_median," [",value_5th,"-",value_95th,"]")) %>% 
  select(category,var,year,year_sd,value,value_sd)

wd_sd_table <- spread(wd_sd_summary %>% select(-value_sd),var,value)
wd_sd_table <- left_join(wd_sd_table,spread(wd_sd_summary %>% select(-value),var,value_sd) %>% select(category,CO2_sd=CO2,GHG_sd=GHG))

wd_sd_table <- wd_sd_table %>% 
  arrange(desc(category)) %>% 
  select(category,year,year_sd,CO2_residual=CO2,CO2_sd,GHG_residual=GHG,GHG_sd)

```

``` {r small_calculations}

## how many scenarios were excluded?
total_scenarios <- data_r1 %>% 
  ungroup() %>% 
  select(model,scenario,category) %>% 
  distinct() %>% 
  group_by(category) %>% 
  summarise(n=n())


## what is the range of non-CO2 GHG emissions at net zero in C1-C3 scenarios ?
non_CO2 <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(value=ifelse(is.na(value),0,value)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>%
  filter(gas!="CO2") %>% 
  group_by(id,category,year) %>% 
  summarise(value=sum(value)) %>% 
  mutate(var="GHG")

non_CO2 <- median_and_range(non_CO2,"var")


## how many scenarios adjust 2020 emissions for COVID?
covid <- wd_scenarios_emissions %>% 
  filter(year==2020) %>% 
  select(id,category) %>% 
  distinct()
cc_expl <- read.xlsx('Data/AR6_Scenarios_Database_metadata_indicators_v1.1_1.xlsx',sheet=2)
covid <- left_join(covid,cc_expl %>% mutate(id=paste0(Model,"|",Scenario)) %>% select(id,COVID),by = join_by(id)) %>% 
  group_by(COVID) %>% 
  summarise(n=n())


## 


```


``` {r summary_table_after_nz}

blarg <- wd_scenarios_emissions %>% 
  filter(year %in% c(2020,2100)) %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  group_by(id,category,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
    mutate(gas="GHG")

blarg <- blarg %>% 
  group_by(id,gas,category) %>% 
  summarise(level=last(value),
            rel_change=(first(value)-last(value))/first(value)) %>% 
  mutate(rel_change=rel_change*100)

blarg <- median_and_range(blarg %>% mutate(value=rel_change),c("gas","category"))

```



```{r residual_gases_sectors_fuels}


## emissions by gas at NZ
wd_gases <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(value=ifelse(is.na(value),0,value)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>% 
  group_by(id,model,scenario,category,year,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## emissions by sector at NZ
wd_sectors <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(value=ifelse(is.na(value),0,value)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>% 
  mutate(sector=as.character(sector)) %>% 
  mutate(sector=ifelse(sector %in% c("Industrial processes","F-Gases","Other"),"Other (Industrial processes, F-gases, other)",sector)) %>% 
  group_by(id,model,scenario,category,year,sector) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## energy by fuel type at NZ
wd_fuels <- data_r1 %>% 
  ungroup() %>% 
  mutate(id=paste0(model,"|",scenario)) %>% 
  select(-region,-unit) %>% 
  filter(var %in% c("Primary Energy",
                    "Primary Energy|Fossil|w/ CCS",
                    "Primary Energy|Coal|w/o CCS",
                    "Primary Energy|Gas|w/o CCS",
                    "Primary Energy|Oil|w/o CCS"))

wd_fuels <- left_join(wd_fuels,wd_check_years,by="id") %>% 
  filter(!is.na(native_net_zero_CO2)) %>% 
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  #mutate(include=ifelse(year==2050,1,0)) %>% 
  filter(include==1) %>% 
  select(-include)

wd_fuels <- spread(wd_fuels,var,value)
wd_fuels <- wd_fuels %>% 
  mutate(`Primary Energy|Renewable & nuclear`=`Primary Energy`-
           `Primary Energy|Fossil|w/ CCS`-
           `Primary Energy|Coal|w/o CCS` -
           `Primary Energy|Gas|w/o CCS` -
           `Primary Energy|Oil|w/o CCS`)

wd_fuels <- gather(wd_fuels,var,value,`Primary Energy`:`Primary Energy|Renewable & nuclear`) %>% 
  filter(var!="Primary Energy")

wd_fuels <- left_join(wd_fuels,data.frame(var=c("Primary Energy|Renewable & nuclear",
                    "Primary Energy|Fossil|w/ CCS",
                    "Primary Energy|Coal|w/o CCS",
                    "Primary Energy|Gas|w/o CCS",
                    "Primary Energy|Oil|w/o CCS"),
                    fuel=c("Renewables, biomass & nuclear",
                             "Fossil with CCS",
                             "Coal",
                             "Gas",
                             "Oil")),by="var")

wd_fuels$fuel <- as.factor(wd_fuels$fuel)
wd_fuels$fuel <- fct_relevel(wd_fuels$fuel,"Renewables, biomass & nuclear","Fossil with CCS","Oil","Gas","Coal")

wd_fuels$category <- as.factor(wd_fuels$category)
wd_fuels$category <- fct_relevel(wd_fuels$category,"C3","C2","C1")

wd_fuels <- wd_fuels %>% 
  mutate(model=ifelse(grepl("IMAGE",model),"IMAGE",model)) %>% 
  mutate(model=ifelse(grepl("REMIND",model),"REMIND",model)) %>% 
  mutate(model=ifelse(grepl("MESSAGE",model),"MESSAGE",model))



## data summaries
## at this point we ignore C1-C3 really
wd_gases_summary <- median_and_range(wd_gases,c("model","gas"))
wd_gases_summary <- rbind(wd_gases_summary,
                          median_and_range(wd_gases,"gas") %>% mutate(model="all"))
wd_gases_summary <- spread(wd_gases_summary,gas,value) %>% 
  arrange(model)

wd_sectors_summary <- median_and_range(wd_sectors,c("model","sector"))
wd_sectors_summary <- rbind(wd_sectors_summary,
                          median_and_range(wd_sectors,"sector") %>% mutate(model="all"))
wd_sectors_summary <- spread(wd_sectors_summary,sector,value) %>% 
  arrange(model)

wd_fuels_extra_vars <- spread(wd_fuels %>% select(-var),fuel,value) %>% 
  mutate(`Fossil total`=Oil+Coal+Gas) %>% 
  mutate(Total=`Fossil total`+`Renewables, biomass & nuclear`+`Fossil with CCS`)
wd_fuels_extra_vars <- gather(wd_fuels_extra_vars,fuel,value,`Renewables, biomass & nuclear`:Total)

wd_fuels_summary <- median_and_range(wd_fuels_extra_vars,c("model","fuel"))
wd_fuels_summary <- rbind(wd_fuels_summary,
                          median_and_range(wd_fuels_extra_vars,"fuel") %>% mutate(model="all"))
wd_fuels_summary$fuel <- as.factor(wd_fuels_summary$fuel)
wd_fuels_summary$fuel <- fct_relevel(wd_fuels_summary$fuel,"Coal","Oil","Gas","Fossil total","Fossil with CCS","Renewables, biomass & nuclear","Total")
wd_fuels_summary <- spread(wd_fuels_summary,fuel,value) %>% 
  arrange(model)

addWorksheet(wb_analysis,"gas_residual_at_nz")
addWorksheet(wb_analysis,"sector_residual_at_nz")
addWorksheet(wb_analysis,"fuel_at_nz")
writeData(wb_analysis, sheet = "gas_residual_at_nz",
          wd_gases_summary, colNames = T, rowNames = F)
writeData(wb_analysis, sheet = "sector_residual_at_nz",
          wd_sectors_summary, colNames = T, rowNames = F)
writeData(wb_analysis, sheet = "fuel_at_nz",
          wd_fuels_summary, colNames = T, rowNames = F)

```

``` {r fuels_check}
 ## what about primary energy supply if we compare across the same year??

wd_fuels_check <- data_r1 %>% 
  ungroup() %>% 
  mutate(id=paste0(model,"|",scenario)) %>% 
  select(-region,-unit) %>% 
  filter(var %in% c("Primary Energy",
                    "Primary Energy|Fossil|w/ CCS",
                    "Primary Energy|Coal|w/o CCS",
                    "Primary Energy|Gas|w/o CCS",
                    "Primary Energy|Oil|w/o CCS"))

wd_fuels_check <- left_join(wd_fuels_check,cc_scenarios %>% mutate(include=1)) %>% 
  filter(year %in% c(2050,2075,2100)) %>% 
  filter(include==1) %>% 
  select(-include)

wd_fuels_check <- spread(wd_fuels_check,var,value)
wd_fuels_check <- wd_fuels_check %>% 
  mutate(`Primary Energy|Renewable & nuclear`=`Primary Energy`-
           `Primary Energy|Fossil|w/ CCS`-
           `Primary Energy|Coal|w/o CCS` -
           `Primary Energy|Gas|w/o CCS` -
           `Primary Energy|Oil|w/o CCS`)

wd_fuels_check <- gather(wd_fuels_check,var,value,`Primary Energy`:`Primary Energy|Renewable & nuclear`) %>% 
  filter(var!="Primary Energy")

wd_fuels_check <- left_join(wd_fuels_check,data.frame(var=c("Primary Energy|Renewable & nuclear",
                    "Primary Energy|Fossil|w/ CCS",
                    "Primary Energy|Coal|w/o CCS",
                    "Primary Energy|Gas|w/o CCS",
                    "Primary Energy|Oil|w/o CCS"),
                    fuel=c("Renewables, biomass & nuclear",
                             "Fossil with CCS",
                             "Coal",
                             "Gas",
                             "Oil")),by="var")

wd_fuels_check <- wd_fuels_check %>% 
  mutate(model=ifelse(grepl("IMAGE",model),"IMAGE",model)) %>% 
  mutate(model=ifelse(grepl("REMIND",model),"REMIND",model)) %>% 
  mutate(model=ifelse(grepl("MESSAGE",model),"MESSAGE",model)) %>% 
  filter(year==2050)

wd_fuels_check_totals <- wd_fuels_check 

wd_fuels_check <- median_and_range(wd_fuels_check,c("model","var"))
wd_fuels_check_totals <- median_and_range(wd_fuels_check_totals,c("var"))
wd_fuels_check <- rbind(wd_fuels_check,wd_fuels_check_totals %>% mutate(model="all"))

wd_fuels_check <- spread(wd_fuels_check,var,value)

addWorksheet(wb_analysis,"fuel_at_2050")
writeData(wb_analysis, sheet = "fuel_at_2050",
          wd_fuels_check, colNames = T, rowNames = F)

```


```{r plot_gases_sectors_fuels,fig.height=9,fig.width=9,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

p1 <- wd_gases %>% ggplot(.,aes(x=id,y=value,fill=gas)) +
  geom_bar(stat="identity",color="#969696") +
  facet_nested(.~model + fct_rev(category),scales="free_x",space="free",switch = "x",
               nest_line = element_line(linetype = 1,color='#636363')) +
  theme_wl() +
  scale_y_continuous(limits=c(0,28),breaks=c(0,5,10,15,20,25)) +
  #scale_fill_manual(values=colors[1:4]) +
  scale_fill_brewer(palette="Greens") +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position="bottom",
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.margin = margin(t=-5),
        strip.background = element_blank(),
        panel.spacing.x=unit(0.4, "lines"),
        panel.border = element_blank(),
        strip.text = element_text(color='#636363'),) +
  labs(title="a. Residual GHG emissions at net zero by gas",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

wd_sectors$sector <- as.factor(wd_sectors$sector)
wd_sectors$sector <- fct_relevel(wd_sectors$sector,"Energy","AFOLU","Other (Industrial processes, F-gases, other)")

p2 <- wd_sectors %>% ggplot(.,aes(x=id,y=value,fill=sector)) +
  geom_bar(stat="identity",color="#969696") +
  facet_nested(.~model + fct_rev(category),scales="free_x",space="free",switch = "x",
               nest_line = element_line(linetype = 1,color='#636363')) +
  theme_wl() +
  scale_y_continuous(limits=c(0,28),breaks=c(0,5,10,15,20,25)) +
  scale_fill_brewer(palette="Blues") +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position="bottom",
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.margin = margin(t=-5),
        strip.background = element_blank(),
        panel.spacing.x=unit(0.4, "lines"),
        panel.border = element_blank(),
        strip.text = element_text(color='#636363'),
        strip.clip = element_blank()
        ) +
  labs(title="b. Residual GHG emissions at net zero by sector",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))


p3 <- wd_fuels %>% ggplot(.,aes(x=id,y=value,fill=fuel)) +
  geom_bar(stat="identity",color="#969696") +
  facet_nested(.~model + fct_rev(category),scales="free_x",space="free",switch = "x",
               nest_line = element_line(linetype = 1,color='#636363')) +
  theme_wl() +
  scale_fill_brewer(palette="Oranges") +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position="bottom",
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.margin = margin(t=-5),
        strip.background = element_blank(),
        panel.spacing.x=unit(0.4, "lines"),
        panel.border = element_blank(),
        strip.text = element_text(color='#636363'),
        strip.clip = element_blank()
        ) +
  labs(title="c. Primary Energy supply at net zero by fuel",
       subtitle=bquote("EJ/yr"))

p1/plot_spacer()/p2/plot_spacer()/p3 + plot_layout(heights=c(5,1,5,1,5))



## save plot data
addWorksheet(wb_figures,"fig_2a_gases")
addWorksheet(wb_figures,"fig_2b_sectors")
addWorksheet(wb_figures,"fig_2c_fuels")

writeData(wb_figures, sheet = "fig_2a_gases",spread(wd_gases,gas,value) 
          %>% arrange(model,desc(category),scenario), colNames = T, rowNames = F)
writeData(wb_figures, sheet = "fig_2b_sectors",spread(wd_sectors,sector,value)
          %>% arrange(model,desc(category),scenario), colNames = T, rowNames = F)
writeData(wb_figures, sheet = "fig_2c_fuels",spread(wd_fuels %>% select(-fuel),var,value) %>% 
            select(-native_net_zero_CO2,-native_net_zero_CO2) %>% 
            select(id,model,scenario,category,year,everything()) %>% 
            arrange(model,desc(category),scenario), colNames = T, rowNames = F)
            


```

```{r plot_subsectors,fig.height=9,fig.width=9,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

## get the scenario data
wd_subsectors <- wd_scenarios_emissions %>%
  filter(var!="Kyoto Gases") %>%
  filter(!grepl("Carbon Sequestration",var)) %>%
  mutate(value=ifelse(is.na(value),0,value)) %>%
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>%
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>%
  group_by(id,model,category,year,sector,var) %>%
  summarise(value=sum(value,na.rm=TRUE))


## generate median scenarios for each

wd_subsectors_total <- wd_subsectors %>% 
  mutate(model="All") %>% 
  mutate(year=ifelse(year!=2020,2050,year)) %>% #2050 here is just a fake year to merge all the nz years
  group_by(model,year,sector,var) %>%
  summarise(percentile_5th = quantile(value, probs = c(0.05)),
            percentile_95th = quantile(value, probs = c(0.95)),
            std=sd(value),
            value=median(value,na.rm=TRUE)) %>% 
  mutate(model="All")

wd_subsectors <- wd_subsectors %>% 
  mutate(year=ifelse(year!=2020,2050,year)) %>% #2050 here is just a fake year to merge all the nz years
  group_by(model,year,sector,var) %>%
  summarise(percentile_5th = quantile(value, probs = c(0.05)),
            percentile_95th = quantile(value, probs = c(0.95)),
            std=sd(value),
            value=median(value,na.rm=TRUE))

## calculate relative and absolute changes for each model and variable
wd_subsectors <- rbind(wd_subsectors,wd_subsectors_total)
wd_subsectors <- wd_subsectors %>% 
  group_by(model,sector,var) %>% 
  mutate(change_rel = (first(value)-last(value))/first(value)) %>% 
  mutate(change_rel_5th = (first(percentile_5th)-last(percentile_5th))/first(percentile_5th)) %>% 
  mutate(change_rel_95th = (first(percentile_95th)-last(percentile_95th))/first(percentile_95th)) %>% 
  mutate(change_rel=-round(change_rel*100,0)) %>% 
  mutate(change_rel_5th=-round(change_rel_5th*100,0)) %>% 
  mutate(change_rel_95th=-round(change_rel_95th*100,0))


## rebase the data so that totals in 2020 vs "2050" are shown
wd_subsectors <- wd_subsectors %>% 
  group_by(model,sector,var) %>% 
  mutate(value_rebased=first(value)-last(value)) %>% 
  mutate(value_rebased=ifelse(year==2050,value,value_rebased))

wd_subsectors <- wd_subsectors %>%
  mutate(value_rebased=ifelse(value_rebased<0,0,value_rebased))

wd_subsectors$year = as.factor(wd_subsectors$year)
wd_subsectors$year <- fct_relevel(wd_subsectors$year,"2020","2050")

p1 <- wd_subsectors %>% 
  filter(model!="All") %>% 
  filter(sector=="Energy") %>% 
  mutate(var=gsub("\\|Energy","",var)) %>% 
  ggplot(.,aes(x=value_rebased,y=reorder(var,value_rebased),alpha=year)) +
  geom_col(color='#636363',fill="#8da0cb") +
  geom_errorbar(data=wd_subsectors %>%
                  filter(model!="All") %>% 
                  filter(year==2050) %>%
                  filter(sector=="Energy") %>%
                  mutate(var=gsub("\\|Energy","",var)),inherit.aes = FALSE,
                aes(xmin=percentile_5th,xmax=percentile_95th,y=reorder(var,value_rebased)),
                width=0.3) +
  geom_text(data=wd_subsectors %>%
              filter(model!="All") %>% 
              filter(sector=="Energy") %>%
              mutate(var=gsub("\\|Energy","",var)) %>% 
              group_by(model,var,change_rel) %>%
              summarise(value=sum(value_rebased)),
            inherit.aes = FALSE,aes(x=value+1,y=var,
                                    label=ifelse(change_rel<0,
                                                 paste0(change_rel,"%"),
                                                 paste0("+",change_rel,"%"))),
                                    hjust=0,size=3) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  scale_alpha_discrete(range=c(0.3,1)) +
  scale_fill_brewer(palette="Blues") +
  facet_grid(.~model) +
  theme_wl() +
  theme(legend.position="none",
        axis.title=element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="a. Energy sector emissions from 2020 to net zero",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

p2 <- wd_subsectors %>%
  filter(model!="All") %>% 
  filter(sector=="AFOLU") %>% 
  mutate(var=gsub("\\|AFOLU","",var)) %>% 
  ggplot(.,aes(x=value_rebased,y=reorder(var,value_rebased),alpha=year)) +
  geom_col(color='#636363',fill="#66c2a5") +
  geom_errorbar(data=wd_subsectors %>%
                  filter(model!="All") %>% 
                  filter(year==2050) %>%
                  filter(sector=="AFOLU") %>% 
                  mutate(var=gsub("\\|AFOLU","",var)),inherit.aes = FALSE,
                aes(xmin=percentile_5th,xmax=percentile_95th,y=reorder(var,value_rebased)),
                width=0.3) +
  geom_text(data=wd_subsectors %>%
              filter(model!="All") %>% 
              filter(sector=="AFOLU") %>%
              mutate(var=gsub("\\|AFOLU","",var)) %>% 
              group_by(model,var,change_rel) %>%
              summarise(value=sum(value_rebased)),
            inherit.aes = FALSE,aes(x=value+1.2,y=var,
                                    label=ifelse(change_rel<0,
                                                 paste0(change_rel,"%"),
                                                 paste0("+",change_rel,"%"))),
                                    hjust=0,size=3) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  scale_alpha_discrete(range=c(0.3,1)) +
  #scale_fill_brewer(palette="Greens") +
  facet_grid(.~model) +
  theme_wl() +
  theme(legend.position="none",
        axis.title=element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="b. AFOLU sector emissions from 2020 to net zero",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

p3 <- wd_subsectors %>% 
  filter(model!="All") %>% 
  filter(sector!="Energy") %>% 
  filter(sector!="AFOLU") %>% 
  mutate(var=gsub("\\|Other","",var)) %>% 
  mutate(var=ifelse(var=="CO2","CO2|Other",var)) %>% 
  ggplot(.,aes(x=value_rebased,y=reorder(var,value_rebased),alpha=year)) +
  geom_col(color='#636363',fill="#fc8d62") +
  geom_errorbar(data=wd_subsectors %>%
                  filter(model!="All") %>% 
                  filter(year==2050) %>% 
                  filter(sector!="Energy") %>% 
                  filter(sector!="AFOLU") %>% 
                  mutate(var=gsub("\\|Other","",var)) %>% 
                  mutate(var=ifelse(var=="CO2","CO2|Other",var)),inherit.aes = FALSE,
                aes(xmin=percentile_5th,xmax=percentile_95th,y=reorder(var,value_rebased)),
                width=0.3) +
  geom_text(data=wd_subsectors %>%
              filter(model!="All") %>% 
              filter(sector!="Energy") %>%
              filter(sector!="AFOLU") %>%
              mutate(var=gsub("\\|Other","",var)) %>%
              mutate(var=ifelse(var=="CO2","CO2|Other",var)) %>%
              group_by(model,var,change_rel) %>%
              summarise(value=sum(value_rebased)),
            inherit.aes = FALSE,aes(x=value+0.4,y=var,
                                    label=ifelse(change_rel<0,
                                                 paste0(change_rel,"%"),
                                                 paste0("+",change_rel,"%"))),
                                    hjust=0,size=3) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  scale_alpha_discrete(range=c(0.3,1)) +
  scale_fill_brewer(palette="Oranges") +
  facet_grid(.~model) +
  theme_wl() +
  theme(legend.position="none",
        axis.title=element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="c. Other sector emissions from 2020 to net zero",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))

p1 / p2 / p3



## save plot data
addWorksheet(wb_figures,"fig_3_subsectors")


writeData(wb_figures, sheet = "fig_3_subsectors",
          wd_subsectors %>% 
            select(sector,model,var,year,value_rebased,percentile_5th,percentile_95th) %>%
            arrange(sector,model,var,year) %>% 
            mutate(year=ifelse(year==2050,"Net Zero","2020")),
  colNames = T, rowNames = F)
            


```

```{r residual_subsectors}

wd_subsectors_summary <- wd_subsectors %>% 
  ungroup() %>% 
  filter(year==2050) %>% 
  mutate(sector=as.character(sector)) %>% 
  mutate(sector=ifelse(sector=="F-Gases","Other",sector)) %>% 
  mutate(sector=ifelse(sector=="Industrial processes","Other",sector)) %>% 
  mutate(change_rel_5th=ifelse(percentile_5th==0,-100,change_rel_5th)) %>% 
  mutate(value=paste0(signif(value,2)," [",signif(percentile_5th,2),"-",signif(percentile_95th,2),"]")) %>% 
  mutate(change_rel=paste0(change_rel," [",change_rel_5th," to ",change_rel_95th,"]")) %>% 
  select(model,sector,var,value,change_rel)

wd_subsectors_summary$sector <- as.factor(wd_subsectors_summary$sector)
wd_subsectors_summary$sector <- fct_relevel(wd_subsectors_summary$sector,
                                            "AFOLU","Energy","Other")

wd_subsectors_summary <- cbind(spread(wd_subsectors_summary %>% 
                                        mutate(model=paste0(model,"_level")) %>% 
                                        select(-change_rel),model,value),
                               spread(wd_subsectors_summary %>% 
                                        mutate(model=paste0(model,"_reduction")) %>% 
                                        select(-value),model,change_rel) %>% 
                                 select(-sector,-var)) %>% 
  arrange(sector,var)


addWorksheet(wb_analysis,"subsector_residual_at_nz")
writeData(wb_analysis, sheet = "subsector_residual_at_nz",
          wd_subsectors_summary, colNames = T, rowNames = F)

```

```{r plot_principal_components,fig.height=6,fig.width=8,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

wd_pca <- wd_scenarios_emissions %>%
  filter(var!="Kyoto Gases") %>%
  filter(!grepl("Carbon Sequestration",var)) %>%
  mutate(value=ifelse(is.na(value),0,value)) %>%
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>% 
  filter(include==1) %>%
  group_by(id,model,var) %>%
  summarise(value=sum(value,na.rm=TRUE))

wd_pca <- spread(wd_pca,var,value)
pca <- prcomp(wd_pca %>% ungroup() %>% select(-id,-model),scale=TRUE)
wd_pca <- cbind(wd_pca %>% select(id,model),pca$x)
pca_variance <-get_eigenvalue(pca)$variance.percent
sum(pca_variance[1:2])


# colors=c("#e6550d","#3182bd","#31a354")
# wd_pca %>% ggplot(.,aes(x=PC1,y=PC2,fill=model)) +
#   geom_point(shape=21,size=3,alpha=0.6) +
#   theme_wl() +
#   scale_fill_manual(values=colors) +
#   theme(legend.title=element_blank()) +
#   labs(title=paste0("Principal components explaining ",signif(sum(pca_variance[1:2]),2), "% of residual\nsubsector emissions variance"))


fviz_pca_biplot(pca, 
                geom.ind = "point",
                pointshape = 21,
                pointsize = 3,
                fill.ind = wd_pca$model,
                col.ind = "black",
                select.var = list(contrib= 12),
                col.var = "black",
                repel = TRUE        # Avoid label overplotting
             ) + 
  theme_wl() +
  xlim(-4,4) +
  ylim(-3,6) +
  theme(legend.title=element_blank()) +
  labs(title=paste0("Principal components and variables explaining\nvariance in residual subsector emissions"))

# fviz_contrib(pca,
#              choice = "var",
#              axes = 1:2,
#              fill="#3182bd") +
#   coord_flip() +
#   theme(axis.text.x = element_text(angle = 0,hjust=0.5),
#         axis.title.y = element_blank())


```

```{r plot_cluster_analysis,fig.height=6,fig.width=8,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

# wd_clusters <- wd_scenarios_emissions %>%
#   filter(var!="Kyoto Gases") %>%
#   filter(!grepl("Carbon Sequestration",var)) %>%
#   mutate(value=ifelse(is.na(value),0,value)) %>%
#   mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>%
#   filter(include==1) %>%
#   group_by(id,category,var) %>%
#   summarise(value=sum(value,na.rm=TRUE))
# 
# wd_clusters <- spread(wd_clusters,var,value) %>%
#   ungroup()
# 
# cc_clusters = wd_clusters %>%
#   select(id) %>% 
#   mutate(no_clusters=NA) %>% 
#   mutate(value=NA)
# 
# for(x in 3:6) {
#   
#   wd_cluster_summary <- kmeans(scale(wd_clusters %>% select(-id,-category)),x,nstart=25)
#   
#   blarg <- cbind(cc_clusters %>% select(id),value=wd_cluster_summary$cluster) %>% 
#     mutate(no_clusters=x)
#   cc_clusters <- rbind(cc_clusters,blarg)
#   
# }
# 
# cc_clusters <- left_join(cc_clusters %>% filter(!is.na(no_clusters)),wd_pca %>% select(id,model,PC1,PC2))
# cc_clusters <- cc_clusters %>% 
#   mutate(label=paste0(no_clusters," Clusters"))
# 
# cc_clusters$value <- as.factor(cc_clusters$value)
# 
# 
# cc_clusters %>% ggplot(.,aes(x=PC1,y=PC2,fill=model)) +
#   geom_point(shape=21,size=3,alpha=0.6) +
#   theme_wl() +
#   facet_wrap(.~label) +
#   #theme(legend.position="none") +
#   labs(title=paste0("Principal components explaining ",signif(sum(pca_variance[1:2]),2), "% of residual subsector emissions variance"))


```


```{r plot_scenario_characteristics,fig.width=8,fig.height=9.5,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}

cc_expl <- read.xlsx('Data/AR6_Scenarios_Database_metadata_indicators_v1.1_1.xlsx',sheet=2)
cc_expl <- cc_expl %>%
  mutate(id=paste0(Model,"|",Scenario)) %>% 
  select(id,Policy_category,Policy_category_name,Project_study,reference=`Literature.Reference.(if.applicable)`,
         Ssp_family,Technology_category_name)

## explanatory factors vs. total residual?
wd_expl <- left_join(wd_scenarios_emissions,cc_expl,by="id") %>% 
  mutate(include=ifelse(year==native_net_zero_CO2,1,0)) %>% 
  filter(include==1) %>% 
  select(-include) %>% 
  filter(var!="Kyoto Gases") %>% 
  filter(!is.na(subsector))

wd_expl <- wd_expl %>% 
  group_by(id,model,category,Policy_category,Policy_category_name,Project_study,reference,
         Ssp_family,Technology_category_name) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(Ssp_family=as.character(Ssp_family)) %>% 
  mutate(Ssp_family=ifelse(Ssp_family=="1","SSP1",Ssp_family)) %>%
  mutate(Ssp_family=ifelse(Ssp_family=="2","SSP2",Ssp_family)) %>% 
  mutate(Ssp_family=as.factor(Ssp_family))


wd_expl <- wd_expl %>% 
  ungroup() %>% 
  select(-category,-Policy_category,-reference)
wd_expl <- gather(wd_expl,key,var,-id,-value,-model)

p1 <- wd_expl %>% 
  ggplot(.,aes(x=value,y=var)) +
  geom_point(shape=21,size=3,alpha=0.5,color="#636363",aes(fill=model)) +
  stat_summary(fun=median,geom="crossbar", color="#636363",width=0.5,show.legend = FALSE) +
  facet_grid(key~.,scales="free_y",space="free",switch="y",
             labeller=as_labeller(c(Policy_category_name="Policy category",
                                    Project_study="Project study",
                                    Ssp_family="SSP family",
                                    Technology_category_name="Technology category"))) +
  scale_y_discrete(limits=rev,labels = function(x) str_wrap(x, width = 25)) +
  theme_wl() +
  theme(legend.position="bottom",
        legend.title=element_blank(),
        axis.title = element_blank(),
        strip.text = element_text(color="#252525"),
        plot.margin = margin(0,0,0,0,"cm"),) +
  labs(title="Residual GHG emissions at net zero vs. scenario characteristics",
       subtitle=bquote("Gt"~CO[2]*"e/yr and fraction of sample"))


## how many scenarios are from the ENGAGE project?
wd_expl_totals <- wd_expl %>% 
  group_by(key,var) %>% 
  summarise(n=n(),
            fraction=n/length(no_scenarios$id)) %>% 
  mutate(fraction=signif(fraction*100,2))

p2 <- wd_expl_totals %>% ggplot(.,aes(x="% of sample",y=var,label=paste0(fraction,"%"))) +
  geom_text(size=4,color="#636363") +
  facet_grid(key~.,scales="free_y",space="free") +
  scale_y_discrete(limits=rev) +
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        axis.text = element_blank(),
        plot.background = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        axis.text.x = element_blank())


p1 + p2 + plot_layout(widths=c(9,1))


wd_expl <- median_and_range(wd_expl,c("key","var"))
wd_expl <- left_join(wd_expl,wd_expl_totals)

addWorksheet(wb_analysis,"explanatory_vars")
writeData(wb_analysis, sheet = "explanatory_vars",
          wd_expl, colNames = T, rowNames = F)


```


```{r plot_residual_after_nz,fig.height=8,fig.width=8,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}


# pd <- pd %>% 
#   mutate(include=ifelse(year==2020,1,0)) %>% 
#   mutate(include=ifelse(year==net_zero_CO2,1,include)) %>% 
#   mutate(include=ifelse(year==2100,1,include)) %>% 
#   filter(include==1)



# pd <- wd_scenarios_emissions %>% 
#   filter(var!="Kyoto Gases") %>% 
#   filter(!grepl("Carbon Sequestration",var)) %>% 
#   mutate(include=ifelse(year>=net_zero_CO2,1,0)) %>% 
#   filter(include==1) %>% 
#   group_by(id,model,scenario,category,year,net_zero_CO2) %>% 
#   summarise(value=sum(value,na.rm=TRUE)) #%>% 
#   group_by(id,model,scenario,category) %>% 
#   summarise(emissions_nz=first(value),
#             emissions_2100=last(value))



# pd <- gather(pd,var,value,-id,-category)
# 
# pd %>% filter(var=="change_rel") %>% ggplot(.,aes(x=value,y=category,fill=category)) +
#   geom_point(shape=21,size=3,alpha=0.6,color="#636363") +
#   theme_wl() +
#   theme(legend.position="none",
#         axis.title = element_blank(),
#         plot.margin = margin(0,0,0,0,"cm"))

# 
# 
# pd %>% ggplot(.,aes(x=emissions_2100,y=emissions_nz))+
#   geom_abline(intercept=0,color="#636363") +
#   geom_point(shape=21,size=3,alpha=0.6,color="#636363",aes(fill=category)) +
#   geom_text(data=data.frame(emissions_nz=c(6,5),
#                             emissions_2100=c(5,6),
#                             label=c("Decrease","Increase")),
#             aes(label=label),
#             color="#636363",
#             angle=35,
#             hjust=0) +
#   facet_wrap(.~category) +
#   theme_wl() +
#   theme(legend.title=element_blank()) +
#   xlim(5,25) +
#   ylim(5,25) +
#   ylab("GHG emissions at net-zero") +
#   xlab("GHG emissions at 2100") +
#   labs(title="Residual GHG emissions after net-zero",
#        subtitle="GtCO2e/yr")
# 
# 
# pd <- wd_scenarios_emissions %>% 
#   filter(var!="Kyoto Gases") %>% 
#   filter(!grepl("Carbon Sequestration",var)) %>% 
#   group_by(id,model,scenario,category,year,net_zero_CO2) %>% 
#   summarise(value=sum(value,na.rm=TRUE))
# 
# pd %>% ggplot(.,aes(x=year,y=value,group=id,color=model)) +
#   geom_line() +
#   facet_grid(category~model) +
#   theme_wl() +
#   theme(legend.position="none") +
#   scale_y_continuous(limits=c(0,60),breaks=c(0,10,20,30,40,50,60))
```

```{r standards_table}

wd_standards <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases")%>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(include=ifelse(year==native_net_zero_CO2,1,0)) %>%
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>% 
  select(-include)

wd_standards <- wd_standards %>% 
  mutate(mapping=ifelse(sector=="AFOLU","AFOLU",NA)) %>% 
  mutate(mapping=ifelse(var=="CO2|Energy|Supply","Power",mapping)) %>% 
  mutate(mapping=ifelse(var=="CO2|Energy|Demand|Industry","Cement/Iron and Steel",mapping)) %>% 
  mutate(mapping=ifelse(var=="CO2|Industrial processes","Cement/Iron and Steel",mapping)) %>% 
  mutate(mapping=ifelse(var=="CO2|Energy|Demand|Residential and Commercial","Buildings",mapping))

## cross-sector total (everything excl. AFOLU)
wd_standards_total <- wd_scenarios_emissions %>% 
  filter(var!="Kyoto Gases")%>% 
  filter(!grepl("Carbon Sequestration",var)) %>% 
  mutate(include=ifelse(year==native_net_zero_CO2,1,0)) %>%
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>% 
  select(-include)

wd_standards_total <- wd_standards_total %>% 
  mutate(mapping=ifelse(sector!="AFOLU","Total",NA))

wd_standards <- rbind(wd_standards,wd_standards_total) %>% 
  filter(!is.na(mapping)) %>% 
  group_by(id,category,year,mapping) %>% 
  summarise(value=sum(value,na.rm=TRUE))

wd_standards <- wd_standards %>% 
  group_by(id,category,mapping) %>% 
  mutate(rel_change=(first(value)-last(value))/first(value)) %>% 
  mutate(rel_change=rel_change*100)

wd_standards <- median_and_range(wd_standards %>% select(id,category,sector=mapping,value=rel_change),c("sector","category"))
wd_standards$category <- fct_relevel(wd_standards$category,"C1","C2","C3")
wd_standards <- spread(wd_standards,category,value)

addWorksheet(wb_analysis,"scenarios_vs_standards")
writeData(wb_analysis, sheet = "scenarios_vs_standards",
          wd_standards, colNames = T, rowNames = F)


```


```{r plot_SoCDR_Ch7,fig.height=6,fig.width=8,fig.path="Results/",dev=c('png', 'pdf', 'svg'),dpi=300}


## get the scenario data
wd_subsectors <- wd_scenarios_emissions %>%
  filter(var!="Kyoto Gases") %>%
  filter(!grepl("Carbon Sequestration",var)) %>%
  mutate(value=ifelse(is.na(value),0,value)) %>%
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>%
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>%
  group_by(id,model,category,year,sector,var) %>%
  summarise(value=sum(value,na.rm=TRUE))


## new sector aggregation
aggregation <- read.xlsx("Data/cc_aggregation_socdr.xlsx")
wd_subsectors <- left_join(wd_subsectors,aggregation)
wd_subsectors <- wd_subsectors %>% 
  group_by(id,model,year,colour,aggregation) %>% 
  summarise(value=sum(value,na.rm=TRUE))

## generate median scenarios for each

wd_subsectors <- wd_subsectors %>% 
  mutate(year=ifelse(year!=2020,2050,year)) %>% #2050 here is just a fake year to merge all the nz years
  group_by(year,colour,aggregation) %>%
  summarise(percentile_5th = quantile(value, probs = c(0.05)),
            percentile_95th = quantile(value, probs = c(0.95)),
            std=sd(value),
            value=median(value,na.rm=TRUE))

## calculate relative and absolute changes for each model and variable
wd_subsectors <- wd_subsectors %>% 
  group_by(colour,aggregation) %>% 
  mutate(change_rel = (first(value)-last(value))/first(value)) %>% 
  mutate(change_rel_5th = (first(percentile_5th)-last(percentile_5th))/first(percentile_5th)) %>% 
  mutate(change_rel_95th = (first(percentile_95th)-last(percentile_95th))/first(percentile_95th)) %>% 
  mutate(change_rel=-round(change_rel*100,0)) %>% 
  mutate(change_rel_5th=-round(change_rel_5th*100,0)) %>% 
  mutate(change_rel_95th=-round(change_rel_95th*100,0))


## rebase the data so that totals in 2020 vs "2050" are shown
wd_subsectors <- wd_subsectors %>% 
  group_by(colour,aggregation) %>% 
  mutate(value_rebased=first(value)-last(value)) %>% 
  mutate(value_rebased=ifelse(year==2050,value,value_rebased))

wd_subsectors <- wd_subsectors %>%
  mutate(value_rebased=ifelse(value_rebased<0,0,value_rebased))

wd_subsectors$year = as.factor(wd_subsectors$year)
wd_subsectors$year <- fct_relevel(wd_subsectors$year,"2020","2050")

wd_subsectors$colour = as.factor(wd_subsectors$colour)
wd_subsectors$colour <- fct_relevel(wd_subsectors$colour,"Energy","AFOLU","Other")

blarg <- wd_subsectors %>%
  filter(year==2020) %>% 
  arrange(desc(colour),value)
blarg$levels = 1
blarg$levels = cumsum(blarg$levels)
wd_subsectors <- left_join(wd_subsectors,blarg)
wd_subsectors$aggregation <- fct_reorder(wd_subsectors$aggregation,wd_subsectors$levels)


p1 <- wd_subsectors %>% 
  filter(aggregation!="Other") %>% 
  ggplot(.,aes(x=value_rebased,y=aggregation,alpha=year,fill=colour)) +
  geom_col(color='#636363') +
  geom_errorbar(data=wd_subsectors %>%
                  filter(aggregation!="Other") %>% 
                  filter(year==2050),inherit.aes = FALSE,
                aes(xmin=percentile_5th,xmax=percentile_95th,y=aggregation),
                width=0.3) +
  geom_text(data=wd_subsectors %>%
              filter(aggregation!="Other") %>% 
              group_by(aggregation,change_rel) %>%
              summarise(value=sum(value_rebased)),
            inherit.aes = FALSE,aes(x=value+1,y=aggregation,
                                    label=ifelse(change_rel<0,
                                                 paste0(change_rel,"%"),
                                                 paste0("+",change_rel,"%"))),
                                    hjust=0,size=3) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  scale_alpha_discrete(range=c(0.3,1)) +
  theme_wl() +
  theme(legend.position="none",
        axis.title=element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="Emissions by sector from 2020 to net zero CO2",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))



## get the scenario data
wd_gases <- wd_scenarios_emissions %>%
  filter(var!="Kyoto Gases") %>%
  filter(gas!="F-Gases") %>% 
  filter(!grepl("Carbon Sequestration",var)) %>%
  mutate(value=ifelse(is.na(value),0,value)) %>%
  mutate(include=ifelse(native_net_zero_CO2==year,1,0)) %>%
  mutate(include=ifelse(year==2020,1,include)) %>% 
  filter(include==1) %>%
  group_by(id,model,category,year,gas) %>%
  summarise(value=sum(value,na.rm=TRUE))

## generate median scenarios

wd_gases <- wd_gases %>% 
  mutate(year=ifelse(year!=2020,2050,year)) %>% #2050 here is just a fake year to merge all the nz years
  group_by(year,gas) %>%
  summarise(percentile_5th = quantile(value, probs = c(0.05)),
            percentile_95th = quantile(value, probs = c(0.95)),
            std=sd(value),
            value=median(value,na.rm=TRUE))


## calculate relative and absolute changes for each model and variable
wd_gases <- wd_gases %>% 
  group_by(gas) %>% 
  mutate(change_rel = (first(value)-last(value))/first(value)) %>% 
  mutate(change_rel_5th = (first(percentile_5th)-last(percentile_5th))/first(percentile_5th)) %>% 
  mutate(change_rel_95th = (first(percentile_95th)-last(percentile_95th))/first(percentile_95th)) %>% 
  mutate(change_rel=-round(change_rel*100,0)) %>% 
  mutate(change_rel_5th=-round(change_rel_5th*100,0)) %>% 
  mutate(change_rel_95th=-round(change_rel_95th*100,0))


## rebase the data so that totals in 2020 vs "2050" are shown
wd_gases <- wd_gases %>% 
  group_by(gas) %>% 
  mutate(value_rebased=first(value)-last(value)) %>% 
  mutate(value_rebased=ifelse(year==2050,value,value_rebased))

wd_gases <- wd_gases %>%
  mutate(value_rebased=ifelse(value_rebased<0,0,value_rebased))

wd_gases$year = as.factor(wd_gases$year)
wd_gases$year <- fct_relevel(wd_gases$year,"2020","2050")

wd_gases$gas <- fct_relevel(wd_gases$gas,"F-Gases","N2O","CH4","CO2")


p2 <- wd_gases %>% 
  ggplot(.,aes(x=value_rebased,y=gas,alpha=year,fill=gas)) +
  geom_col(color='#636363',fill='#969696') +
  geom_errorbar(data=wd_gases %>%
                  filter(year==2050),inherit.aes = FALSE,
                aes(xmin=percentile_5th,xmax=percentile_95th,y=gas),
                width=0.3) +
  geom_text(data=wd_gases %>%
              group_by(gas,change_rel) %>%
              summarise(value=sum(value_rebased)),
            inherit.aes = FALSE,aes(x=value+1,y=gas,
                                    label=ifelse(change_rel<0,
                                                 paste0(change_rel,"%"),
                                                 paste0("+",change_rel,"%"))),
                                    hjust=0,size=3) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.25))) +
  scale_alpha_discrete(range=c(0.3,1)) +
  theme_wl() +
  theme(legend.position="none",
        axis.title=element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="Emissions by gas from 2020 to net zero CO2",
       subtitle=bquote("Gt"~CO[2]*"e/yr"))



p2 / p1 + plot_layout(heights=c(2,6))




```

``` {r save}

# 
# addWorksheet(wb_analysis,"recalcd_vs_native_net_emissions")
# writeData(wb_analysis, sheet = "recalcd_vs_native_net_emissions",
#           test_residual %>% select(-difference_abs), colNames = T, rowNames = F)


saveWorkbook(wb_figures,"Results/residual-emissions-ERL-figure-data.xlsx",overwrite=T)
saveWorkbook(wb_analysis,"Results/residual-emissions-ERL-analysis.xlsx",overwrite=T)


write.csv(wd_scenarios_emissions %>%
             filter(var!="Kyoto Gases") %>%
             filter(!grepl("Carbon Sequestration",var)),
          file="Results/residual-emissions-ERL-processed-data.csv",sep=";")


```